from __future__ import annotations


ADVISOR_BETA_HEADER = ""
AFK_MODE_BETA_HEADER = ""
BEDROCK_EXTRA_PARAMS_HEADERS: list[str] = []
CLAUDE_CODE_20250219_BETA_HEADER = ""
CLI_INTERNAL_BETA_HEADER = ""
CONTEXT_1M_BETA_HEADER = ""
CONTEXT_MANAGEMENT_BETA_HEADER = ""
EFFORT_BETA_HEADER = ""
FAST_MODE_BETA_HEADER = ""
INTERLEAVED_THINKING_BETA_HEADER = ""
PROMPT_CACHING_SCOPE_BETA_HEADER = ""
REDACT_THINKING_BETA_HEADER = ""
STRUCTURED_OUTPUTS_BETA_HEADER = ""
SUMMARIZE_CONNECTOR_TEXT_BETA_HEADER = ""
TASK_BUDGETS_BETA_HEADER = ""
TOKEN_EFFICIENT_TOOLS_BETA_HEADER = ""
TOOL_SEARCH_BETA_HEADER_1P = ""
TOOL_SEARCH_BETA_HEADER_3P = ""
VERTEX_COUNT_TOKENS_ALLOWED_BETAS: list[str] = []
WEB_SEARCH_BETA_HEADER = ""


__all__ = [name for name in globals() if name.isupper()]
