from __future__ import annotations


BYTES_PER_TOKEN = 4
DEFAULT_MAX_RESULT_SIZE_CHARS = 30_000
MAX_TOOL_RESULTS_PER_MESSAGE_CHARS = 120_000
MAX_TOOL_RESULT_BYTES = 512 * 1024
MAX_TOOL_RESULT_TOKENS = 30_000
TOOL_SUMMARY_MAX_LENGTH = 4_000


__all__ = [name for name in globals() if name.isupper()]
